CREATE DATABASE SISTEMA_A
--DROP DATABASE SISTEMA_A

USE SISTEMA_A

CREATE TABLE CONTATOS (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(255)
	, EMAIL VARCHAR(255) UNIQUE
	, TELEFONE VARCHAR(255)
	, DATA_NASCIMENTO DATE
	, ID_INTEGRACAO_SISTEMA_B INT 
	, STATUS_INTEGRACAO_B VARCHAR(255)
)

INSERT INTO CONTATOS (NOME, EMAIL, TELEFONE, DATA_NASCIMENTO) VALUES 
('Jefferson','jefferson@wittel.com', '11987654321', '1997-08-19')
, ('Ábner','abner@wittel.com', '11987651234', CONVERT(varchar, getdate(), 103))

--DELETE FROM CONTATOS --APENAS DELETA OS REGISTROS
--TRUNCATE TABLE CONTATOS --ESTE COMANDO RESETA OS ID's
SELECT * FROM CONTATOS

--PARA FORMATAR A DATA YYYY-MM-DD
--SELECT CONVERT(varchar, getdate(), 23)
--PARA FORMATAR DD/MM/YYYY
--select convert(varchar, getdate(), 103)

--ALTER TABLE CONTATOS ALTER COLUMN NOME NVARCHAR(255);

--====================================================================================================--

CREATE DATABASE SISTEMA_B

USE SISTEMA_B

CREATE TABLE CONTATOS (
	ID INT IDENTITY(1000,1) PRIMARY KEY
	, NOME VARCHAR(255)
	, EMAIL VARCHAR(255) UNIQUE
	, TELEFONE VARCHAR(255)
	, DATA_NASCIMENTO DATE
	, ID_SISTEMA_A INT 
)

--DROP TABLE CONTATOS

SELECT * FROM CONTATOS